name: Build Theos Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git /Users/runner/work/fasfsaaw/fasfsaaw/theos
          rm -rf /Users/runner/work/fasfsaaw/fasfsaaw/theos/sdks
          git clone --depth 1 https://github.com/theos/sdks.git /Users/runner/work/fasfsaaw/fasfsaaw/theos/sdks

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1 THEOS=/Users/runner/work/fasfsaaw/fasfsaaw/theos

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OzonFakeBalance-deb
          path: packages/*.deb
