name: Build Theos Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        uses: theos/setup-theos-action@v1
      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: OzonFakeBalance-deb
          path: packages/*.deb