name: Build Theos Tweak

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git perl clang libssl-dev

      - name: Install Theos and SDK
        run: |
          git clone --recursive https://github.com/theos/theos.git /home/runner/theos
          curl -sL https://github.com/theos/sdks/releases/download/v13.0/iPhoneOS16.5.sdk.tar.xz | tar -xJ -C /home/runner/theos/sdks

      - name: Build Tweak
        run: |
          export THEOS=/home/runner/theos
          make package FINALPACKAGE=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OzonFakeBalance-deb
          path: packages/*.deb
